### ISSUE TITLE
Avcheckning av "Markera (o)avslutade" avmarkerar allt...

### ISSUE THREAD

**Issue by Gosha** [Niler851/studentportalen-extended#2]
...istället för att bara avmarkera (o)avslutade kurser.

Antar att det behövs lite mer i else-satserna här:

https://github.com/Niler851/studentportalen-extended/blob/d5df470eceb143cbc029d0ed62cca5e6be82af97/app/studentportalen.js#L245-L266
och här
https://github.com/Niler851/studentportalen-extended/blob/d5df470eceb143cbc029d0ed62cca5e6be82af97/app/studentportalen.js#L273-L294

**Comment by note89** [comment]
True that, fixar det.

**Comment by Niler851** [comment]
Done
https://github.com/Niler851/studentportalen-extended/commit/1b7df52e09ac4dc25493d6aef616fb5f90e666fe?diff=split

**Comment by note89** [comment]
Done
https://github.com/Niler851/studentportalen-extended/commit/1b7df52e09ac4dc25493d6aef616fb5f90e666fe?diff=split
