### ISSUE TITLE
Kursnivåer borde läggas till

### ISSUE THREAD

**Issue by ghost** [Niler851/studentportalen-extended#5]
Läser kurser på B-nivå, finns G1, G2 och A-nivå att välja på.

**Comment by note89** [comment]
Där ser man, hade ingen aning om att de fanns. Kan du länka en sånn kurs.

**Comment by ghost** [comment]
http://kdb-5.liu.se/liu/fil/kp_detail_print_sv.lasso?&ID=2017767

**Comment by note89** [comment]
commit d096c18c9e619d28b23eaaf1672a2225ec445526
Lägger till kursnivå B. 

Tack för att du sa till !
Tveka inte och komma med en pullrequest.

**Comment by note89** [comment]
Tar nån timme innan updateringen blir tillgänglig.
